services:
    laravel.test:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        platform: linux/arm64/v8
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        entrypoint: /usr/local/bin/entrypoint.sh
        depends_on:
            - mysql
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - "./default.conf:/etc/nginx/conf.d/default.conf"
            - ".:/var/www/html"
        depends_on:
            - laravel.test
        networks:
            - sail
    mysql:
        image: "mysql:8"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
